management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    com:
      tanzu:
        demo: DEBUG

server:
  port: 8080
